version: '2'
services:
  testproject1-app:
    image: testproject1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://testproject1-postgresql:5432/TestProject1
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8008:8008
  testproject1-postgresql:
    extends:
      file: postgresql.yml
      service: testproject1-postgresql
